@startuml

[Site] --> [SiteChat]

[SiteChat] --> [SendMessageYaFn]

[SiteChat] ---> [S3Bucked]: read a reply, repeat

[SendMessageYaFn] --> [TelegramChanelInput]

[TelegramChanelOutput] --> [UpdatesHandlerYaFn]

[UpdatesHandlerYaFn] --> [S3Bucked]

[CleanUpYaFn] --> [S3Bucked]

@enduml
