@startuml
component S3MessagesBucket
component S3TgMessagesBucket
component S3OrgBucket
component SiteChat
component TgSupportChat

component SiteMessagesHandlerFn #LightBlue
component TgMessagesHandlerFn #LightBlue

SiteMessagesHandlerFn --> S3MessagesBucket
SiteMessagesHandlerFn --> S3OrgBucket
SiteMessagesHandlerFn --> TgSupportChat


TgMessagesHandlerFn --> S3TgMessagesBucket
TgMessagesHandlerFn --> S3MessagesBucket

SiteChat --> SiteMessagesHandlerFn

S3MessagesBucket --> SiteChat

@enduml
