@startuml

Alice -> TgSupportChat: sent message2


TgSupportChat -> TgBot: update event
TgBot -> TgBucket: read last message
TgBucket --> TgBot
...

TgBot -> TgBucket: upload new message

TgBot -> S3MessagesBucket: read last message
S3MessagesBucket --> TgBot

...

TgBot -> TgBot: merge tg history with shared list

TgBot -> S3MessagesBucket: upload new state with message2

@enduml
