@startuml


BackOfficeStuff -> BotInstructionSite: register new account
BotInstructionSite --> BackOfficeStuff

...

BackOfficeStuff -> BotInstructionSite: register domain name (security)
BotInstructionSite --> BackOfficeStuff

...

BackOfficeStuff -> BotInstructionSite: add avatar, logo, construct action form, operators tg ids
BotInstructionSite --> BackOfficeStuff

...

BackOfficeStuff -> BotInstructionSite: add default contacts if operator is not available
BotInstructionSite --> BackOfficeStuff
...

BackOfficeStuff -> BotInstructionSite: get app id + secret token
BotInstructionSite --> BackOfficeStuff
deactivate BackOfficeStuff

...

BackOfficeStuff -> ClientOfficeSite: inject html code for widgets
activate BackOfficeStuff
ClientOfficeSite --> BackOfficeStuff
deactivate BackOfficeStuff


BackOfficeStuff -> TgSupportChat: create support chat then add discussion group
activate BackOfficeStuff
TgSupportChat --> BackOfficeStuff
BackOfficeStuff -> TgSupportChat: add bot
TgSupportChat --> BackOfficeStuff

BackOfficeStuff -> TgSupportChat: add app id and secret token once
TgSupportChat --> BackOfficeStuff
deactivate BackOfficeStuff


@enduml
