@startuml
actor User

User -> SiteChat: message
activate SiteChat

SiteChat -> SiteChat: generate unique guid

SiteChat -> SendFn: send message
activate SendFn
SendFn -> TgSupportChat: create new formatted chanel post with guid
SendFn -> S3MessagesBucket: init: create new file in bucket with guid, then save message there
S3MessagesBucket --> SiteChat: ok
deactivate SendFn

SiteChat --> User: Ok. Plz wait free operator

deactivate SiteChat
@enduml
