@startuml
actor User

User -> SiteChat: opens chat

group repeat/timer
SiteChat -> S3MessagesBucket: through http read replies by guid
S3MessagesBucket --> SiteChat: status == inWork
end

SiteChat --> SiteChat: operator got to work state

...

group repeat/timer
SiteChat -> S3MessagesBucket: through http read replies by guid
S3MessagesBucket --> SiteChat: replies array ? has new
end

SiteChat --> SiteChat: you have a message state

deactivate SiteChat
@enduml
