@startuml
actor User

group repeat/timer
SiteChat -> S3Bucket: through http read replies by messageId
S3Bucket --> SiteChat: status
SiteChat --> User: operator gets to work
end

...

group repeat/timer
SiteChat -> S3Bucket: through http read replies by messageId
S3Bucket --> SiteChat: replies array
SiteChat --> User: you have a message
end

deactivate SiteChat
@enduml
